// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFD9YF1CsTUyg0Q2G-iBldmpemR4Fkwnw',
    appId: '1:440209417924:web:b14d7bf5624a481590cb91',
    messagingSenderId: '440209417924',
    projectId: 'wslc-256',
    authDomain: 'wslc-256.firebaseapp.com',
    storageBucket: 'wslc-256.appspot.com',
    measurementId: 'G-8CM1N6JJ0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_zhmd9nYVjVWebje9HNLSGkpLrIt-MDQ',
    appId: '1:440209417924:android:9e203b24cb3ec8fd90cb91',
    messagingSenderId: '440209417924',
    projectId: 'wslc-256',
    storageBucket: 'wslc-256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfHH8Y5wQUy6YOr1MK42c-rhNhMcnbHyU',
    appId: '1:440209417924:ios:53a7400375210fb690cb91',
    messagingSenderId: '440209417924',
    projectId: 'wslc-256',
    storageBucket: 'wslc-256.appspot.com',
    iosBundleId: 'com.example.wslc256',
  );
}
